/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { DistributorInterface, DistributorInterfaceInterface } from '../DistributorInterface';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'transferStabilityFee',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
];

export class DistributorInterface__factory {
  static readonly abi = _abi;
  static createInterface(): DistributorInterfaceInterface {
    return new utils.Interface(_abi) as DistributorInterfaceInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): DistributorInterface {
    return new Contract(address, _abi, signerOrProvider) as DistributorInterface;
  }
}
