/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { DomiInterface, DomiInterfaceInterface } from '../DomiInterface';

const _abi = [
  {
    inputs: [],
    name: 'getStabilityFee',
    outputs: [
      {
        internalType: 'uint256',
        name: 'stabilityFee',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class DomiInterface__factory {
  static readonly abi = _abi;
  static createInterface(): DomiInterfaceInterface {
    return new utils.Interface(_abi) as DomiInterfaceInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): DomiInterface {
    return new Contract(address, _abi, signerOrProvider) as DomiInterface;
  }
}
