/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  HomePriceCalculator,
  HomePriceCalculatorInterface,
} from "../HomePriceCalculator";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "housePrice",
        type: "uint256",
      },
    ],
    name: "HomePriceReceived",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "a",
        type: "string",
      },
      {
        internalType: "string",
        name: "b",
        type: "string",
      },
    ],
    name: "compareStrings",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "postalCode",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "streetName",
        type: "string",
      },
    ],
    name: "determineHomePrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610341806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633c2647c71461003b578063bed34bba14610064575b600080fd5b61004e610049366004610229565b610084565b60405161005b91906102a8565b60405180910390f35b6100776100723660046101c8565b6100ee565b60405161005b919061029d565b60008061271090506100b5836040518060400160405280600781526020016613dc98da185c9960ca1b8152506100ee565b156100c9576100c6612710826102b1565b90505b6100d46002856102d5565b6100e7576100e46103e8826102b1565b90505b9392505050565b6000816040516020016101019190610264565b60405160208183030381529060405280519060200120836040516020016101289190610264565b6040516020818303038152906040528051906020012014905092915050565b600082601f830112610157578081fd5b813567ffffffffffffffff80821115610172576101726102f5565b604051601f8301601f191681016020018281118282101715610196576101966102f5565b6040528281528483016020018610156101ad578384fd5b82602086016020830137918201602001929092529392505050565b600080604083850312156101da578182fd5b823567ffffffffffffffff808211156101f1578384fd5b6101fd86838701610147565b93506020850135915080821115610212578283fd5b5061021f85828601610147565b9150509250929050565b6000806040838503121561023b578182fd5b82359150602083013567ffffffffffffffff811115610258578182fd5b61021f85828601610147565b60008251815b81811015610284576020818601810151858301520161026a565b818111156102925782828501525b509190910192915050565b901515815260200190565b90815260200190565b600082198211156102d057634e487b7160e01b81526011600452602481fd5b500190565b6000826102f057634e487b7160e01b81526012600452602481fd5b500690565b634e487b7160e01b600052604160045260246000fdfea26469706673582212207b46f601cbd38bd12288f6ddf22c64c833aef5dc9385c3806693cb08398d460764736f6c63430008000033";

export class HomePriceCalculator__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<HomePriceCalculator> {
    return super.deploy(overrides || {}) as Promise<HomePriceCalculator>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): HomePriceCalculator {
    return super.attach(address) as HomePriceCalculator;
  }
  connect(signer: Signer): HomePriceCalculator__factory {
    return super.connect(signer) as HomePriceCalculator__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HomePriceCalculatorInterface {
    return new utils.Interface(_abi) as HomePriceCalculatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HomePriceCalculator {
    return new Contract(address, _abi, signerOrProvider) as HomePriceCalculator;
  }
}
