/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  MonthlyPaymentsCalculatorInterface,
  MonthlyPaymentsCalculatorInterfaceInterface,
} from "../MonthlyPaymentsCalculatorInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "homeId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "renterAddress",
        type: "address",
      },
    ],
    name: "calculatePayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class MonthlyPaymentsCalculatorInterface__factory {
  static readonly abi = _abi;
  static createInterface(): MonthlyPaymentsCalculatorInterfaceInterface {
    return new utils.Interface(
      _abi
    ) as MonthlyPaymentsCalculatorInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MonthlyPaymentsCalculatorInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MonthlyPaymentsCalculatorInterface;
  }
}
