/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { PrincipalInterface, PrincipalInterfaceInterface } from '../PrincipalInterface';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'distributeSavingsRate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];

export class PrincipalInterface__factory {
  static readonly abi = _abi;
  static createInterface(): PrincipalInterfaceInterface {
    return new utils.Interface(_abi) as PrincipalInterfaceInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): PrincipalInterface {
    return new Contract(address, _abi, signerOrProvider) as PrincipalInterface;
  }
}
