/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { ReservesInterface, ReservesInterfaceInterface } from '../ReservesInterface';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'transferBuffer',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
];

export class ReservesInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ReservesInterfaceInterface {
    return new utils.Interface(_abi) as ReservesInterfaceInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ReservesInterface {
    return new Contract(address, _abi, signerOrProvider) as ReservesInterface;
  }
}
