/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HomePriceCalculatorInterface extends ethers.utils.Interface {
  functions: {
    "compareStrings(string,string)": FunctionFragment;
    "determineHomePrice(uint256,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "compareStrings",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "determineHomePrice",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "compareStrings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "determineHomePrice",
    data: BytesLike
  ): Result;

  events: {
    "HomePriceReceived(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "HomePriceReceived"): EventFragment;
}

export type HomePriceReceivedEvent = TypedEvent<
  [BigNumber] & { housePrice: BigNumber }
>;

export class HomePriceCalculator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HomePriceCalculatorInterface;

  functions: {
    compareStrings(
      a: string,
      b: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    determineHomePrice(
      postalCode: BigNumberish,
      streetName: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  compareStrings(
    a: string,
    b: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  determineHomePrice(
    postalCode: BigNumberish,
    streetName: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    compareStrings(
      a: string,
      b: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    determineHomePrice(
      postalCode: BigNumberish,
      streetName: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "HomePriceReceived(uint256)"(
      housePrice?: null
    ): TypedEventFilter<[BigNumber], { housePrice: BigNumber }>;

    HomePriceReceived(
      housePrice?: null
    ): TypedEventFilter<[BigNumber], { housePrice: BigNumber }>;
  };

  estimateGas: {
    compareStrings(
      a: string,
      b: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    determineHomePrice(
      postalCode: BigNumberish,
      streetName: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    compareStrings(
      a: string,
      b: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    determineHomePrice(
      postalCode: BigNumberish,
      streetName: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
